//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{

public sealed partial class TableRoom
{
    private readonly Dictionary<int, TableRoomData> _dataMap;
    private readonly List<TableRoomData> _dataList;
    
    public TableRoom(JSONNode _json)
    {
        _dataMap = new Dictionary<int, TableRoomData>();
        _dataList = new List<TableRoomData>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = TableRoomData.DeserializeTableRoomData(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, TableRoomData> DataMap => _dataMap;
    public List<TableRoomData> DataList => _dataList;

    public TableRoomData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TableRoomData Get(int key) => _dataMap[key];
    public TableRoomData this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}