//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{

public sealed partial class TableTips
{
    private readonly Dictionary<int, TableTipsData> _dataMap;
    private readonly List<TableTipsData> _dataList;
    
    public TableTips(JSONNode _json)
    {
        _dataMap = new Dictionary<int, TableTipsData>();
        _dataList = new List<TableTipsData>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = TableTipsData.DeserializeTableTipsData(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, TableTipsData> DataMap => _dataMap;
    public List<TableTipsData> DataList => _dataList;

    public TableTipsData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TableTipsData Get(int key) => _dataMap[key];
    public TableTipsData this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}