//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{

public sealed partial class TableNpc
{
    private readonly Dictionary<int, TableNpcData> _dataMap;
    private readonly List<TableNpcData> _dataList;
    
    public TableNpc(JSONNode _json)
    {
        _dataMap = new Dictionary<int, TableNpcData>();
        _dataList = new List<TableNpcData>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = TableNpcData.DeserializeTableNpcData(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, TableNpcData> DataMap => _dataMap;
    public List<TableNpcData> DataList => _dataList;

    public TableNpcData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TableNpcData Get(int key) => _dataMap[key];
    public TableNpcData this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}