//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{

public sealed partial class TableRoomData :  Bright.Config.BeanBase 
{
    public TableRoomData(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["name"].IsString) { throw new SerializationException(); }  Name = _json["name"]; }
        { if(!_json["pos"].IsNumber) { throw new SerializationException(); }  Pos = _json["pos"]; }
        { if(!_json["modle"].IsString) { throw new SerializationException(); }  Modle = _json["modle"]; }
        PostInit();
    }

    public TableRoomData(int id, string name, int pos, string modle ) 
    {
        this.Id = id;
        this.Name = name;
        this.Pos = pos;
        this.Modle = modle;
        PostInit();
    }

    public static TableRoomData DeserializeTableRoomData(JSONNode _json)
    {
        return new TableRoomData(_json);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 位置
    /// </summary>
    public int Pos { get; private set; }
    /// <summary>
    /// 模型
    /// </summary>
    public string Modle { get; private set; }

    public const int __ID__ = -1269554957;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Pos:" + Pos + ","
        + "Modle:" + Modle + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
