//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{

public sealed partial class TableAttackData :  Bright.Config.BeanBase 
{
    public TableAttackData(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["name"].IsString) { throw new SerializationException(); }  Name = _json["name"]; }
        { if(!_json["score"].IsNumber) { throw new SerializationException(); }  Score = _json["score"]; }
        PostInit();
    }

    public TableAttackData(int id, string name, int score ) 
    {
        this.Id = id;
        this.Name = name;
        this.Score = score;
        PostInit();
    }

    public static TableAttackData DeserializeTableAttackData(JSONNode _json)
    {
        return new TableAttackData(_json);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 得分
    /// </summary>
    public int Score { get; private set; }

    public const int __ID__ = 1581110368;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Score:" + Score + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
