//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using SimpleJSON;

namespace cfg
{
   
public sealed partial class Tables
{
    public TableScore TableScore {get; }
    public TableAttack TableAttack {get; }
    public TableTips TableTips {get; }
    public TableWepon TableWepon {get; }
    public TableLaguage TableLaguage {get; }
    public TableScene TableScene {get; }
    public TableRoom TableRoom {get; }
    public TableNpc TableNpc {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TableScore = new TableScore(loader("tablescore")); 
        tables.Add("TableScore", TableScore);
        TableAttack = new TableAttack(loader("tableattack")); 
        tables.Add("TableAttack", TableAttack);
        TableTips = new TableTips(loader("tabletips")); 
        tables.Add("TableTips", TableTips);
        TableWepon = new TableWepon(loader("tablewepon")); 
        tables.Add("TableWepon", TableWepon);
        TableLaguage = new TableLaguage(loader("tablelaguage")); 
        tables.Add("TableLaguage", TableLaguage);
        TableScene = new TableScene(loader("tablescene")); 
        tables.Add("TableScene", TableScene);
        TableRoom = new TableRoom(loader("tableroom")); 
        tables.Add("TableRoom", TableRoom);
        TableNpc = new TableNpc(loader("tablenpc")); 
        tables.Add("TableNpc", TableNpc);
        PostInit();

        TableScore.Resolve(tables); 
        TableAttack.Resolve(tables); 
        TableTips.Resolve(tables); 
        TableWepon.Resolve(tables); 
        TableLaguage.Resolve(tables); 
        TableScene.Resolve(tables); 
        TableRoom.Resolve(tables); 
        TableNpc.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TableScore.TranslateText(translator); 
        TableAttack.TranslateText(translator); 
        TableTips.TranslateText(translator); 
        TableWepon.TranslateText(translator); 
        TableLaguage.TranslateText(translator); 
        TableScene.TranslateText(translator); 
        TableRoom.TranslateText(translator); 
        TableNpc.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
